import { MD3LightTheme, MD3DarkTheme } from 'react-native-paper'

// SafarGo Brand Colors (Algérie)
const colors = {
  primary: '#006233',
  primaryContainer: '#dcfce7',
  secondary: '#D21034',
  secondaryContainer: '#fee2e2',
  tertiary: '#f59e0b',
  tertiaryContainer: '#fef3c7',
  surface: '#ffffff',
  surfaceVariant: '#f3f4f6',
  background: '#f9fafb',
  error: '#ef4444',
  errorContainer: '#fee2e2',
  onPrimary: '#ffffff',
  onPrimaryContainer: '#052e16',
  onSecondary: '#ffffff',
  onSecondaryContainer: '#450a0a',
  onTertiary: '#ffffff',
  onTertiaryContainer: '#451a03',
  onSurface: '#111827',
  onSurfaceVariant: '#374151',
  onBackground: '#111827',
  onError: '#ffffff',
  onErrorContainer: '#7f1d1d',
  outline: '#d1d5db',
  outlineVariant: '#e5e7eb',
  shadow: '#000000',
  scrim: '#000000',
  inverseSurface: '#1f2937',
  inverseOnSurface: '#f9fafb',
  inversePrimary: '#86efac',
  elevation: {
    level0: 'transparent',
    level1: '#ffffff',
    level2: '#ffffff',
    level3: '#ffffff',
    level4: '#ffffff',
    level5: '#ffffff',
  },
  surfaceDisabled: 'rgba(17, 24, 39, 0.12)',
  onSurfaceDisabled: 'rgba(17, 24, 39, 0.38)',
  backdrop: 'rgba(0, 0, 0, 0.4)',
}

// Tourism category colors
const tourismColors = {
  beach: '#0ea5e9',
  waterfall: '#06b6d4',
  mountain: '#8b5cf6',
  desert: '#f59e0b',
  heritage: '#ef4444',
  food: '#f97316',
  park: '#22c55e',
  oasis: '#10b981',
  medina: '#6366f1',
  lake: '#3b82f6',
  viewpoint: '#ec4899',
}

export const theme = {
  ...MD3LightTheme,
  colors,
  tourismColors,
  fonts: {
    ...MD3LightTheme.fonts,
    default: {
      fontFamily: 'Inter',
      fontWeight: '400' as const,
    },
    medium: {
      fontFamily: 'Inter-Medium',
      fontWeight: '500' as const,
    },
    semiBold: {
      fontFamily: 'Inter-SemiBold',
      fontWeight: '600' as const,
    },
    bold: {
      fontFamily: 'Inter-Bold',
      fontWeight: '700' as const,
    },
    arabic: {
      fontFamily: 'Cairo',
      fontWeight: '400' as const,
    },
    arabicMedium: {
      fontFamily: 'Cairo-Medium',
      fontWeight: '500' as const,
    },
    arabicSemiBold: {
      fontFamily: 'Cairo-SemiBold',
      fontWeight: '600' as const,
    },
    arabicBold: {
      fontFamily: 'Cairo-Bold',
      fontWeight: '700' as const,
    },
  },
  roundness: 12,
}

export const darkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: '#86efac',
    primaryContainer: '#14532d',
    secondary: '#fca5a5',
    secondaryContainer: '#7f1d1d',
    tertiary: '#fbbf24',
    tertiaryContainer: '#451a03',
    surface: '#1f2937',
    surfaceVariant: '#374151',
    background: '#111827',
    error: '#f87171',
    errorContainer: '#7f1d1d',
    onPrimary: '#052e16',
    onPrimaryContainer: '#dcfce7',
    onSecondary: '#450a0a',
    onSecondaryContainer: '#fee2e2',
    onTertiary: '#451a03',
    onTertiaryContainer: '#fef3c7',
    onSurface: '#f9fafb',
    onSurfaceVariant: '#d1d5db',
    onBackground: '#f9fafb',
    onError: '#7f1d1d',
    onErrorContainer: '#fee2e2',
    outline: '#6b7280',
    outlineVariant: '#4b5563',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#f9fafb',
    inverseOnSurface: '#1f2937',
    inversePrimary: '#006233',
    elevation: {
      level0: 'transparent',
      level1: '#1f2937',
      level2: '#374151',
      level3: '#4b5563',
      level4: '#6b7280',
      level5: '#9ca3af',
    },
    surfaceDisabled: 'rgba(249, 250, 251, 0.12)',
    onSurfaceDisabled: 'rgba(249, 250, 251, 0.38)',
    backdrop: 'rgba(0, 0, 0, 0.4)',
  },
  tourismColors,
  fonts: theme.fonts,
  roundness: 12,
}

export type AppTheme = typeof theme