export const PLACE_TYPES = {
  BEACH: { label: 'Plage', icon: '🏖️', color: '#3B82F6' },
  WATERFALL: { label: 'Cascade', icon: '💧', color: '#06B6D4' },
  MOUNTAIN: { label: 'Montagne', icon: '⛰️', color: '#10B981' },
  DESERT: { label: 'Désert', icon: '🏜️', color: '#F59E0B' },
  HERITAGE: { label: 'Patrimoine', icon: '🏛️', color: '#8B5CF6' },
  MUSEUM: { label: 'Musée', icon: '🏛️', color: '#6366F1' },
  FOOD: { label: 'Gastronomie', icon: '🍽️', color: '#EF4444' },
  VIEWPOINT: { label: 'Panorama', icon: '👁️', color: '#EC4899' },
  PARK: { label: 'Parc', icon: '🌳', color: '#22C55E' },
  OASIS: { label: 'Oasis', icon: '🌴', color: '#14B8A6' },
  MEDINA: { label: 'Médina', icon: '🕌', color: '#A855F7' },
  LAKE: { label: 'Lac', icon: '🏞️', color: '#0EA5E9' },
} as const

export const WILAYAS = [
  'Adrar',
  'Chlef',
  'Laghouat',
  'Oum El Bouaghi',
  'Batna',
  'Béjaïa',
  'Biskra',
  'Béchar',
  'Blida',
  'Bouira',
  'Tamanrasset',
  'Tébessa',
  'Tlemcen',
  'Tiaret',
  'Tizi Ouzou',
  'Alger',
  'Djelfa',
  'Jijel',
  'Sétif',
  'Saïda',
  'Skikda',
  'Sidi Bel Abbès',
  'Annaba',
  'Guelma',
  'Constantine',
  'Médéa',
  'Mostaganem',
  'M\'Sila',
  'Mascara',
  'Ouargla',
  'Oran',
  'El Bayadh',
  'Illizi',
  'Bordj Bou Arreridj',
  'Boumerdès',
  'El Tarf',
  'Tindouf',
  'Tissemsilt',
  'El Oued',
  'Khenchela',
  'Souk Ahras',
  'Tipaza',
  'Mila',
  'Aïn Defla',
  'Naâma',
  'Aïn Témouchent',
  'Ghardaïa',
  'Relizane',
  'Timimoun',
  'Bordj Badji Mokhtar',
  'Ouled Djellal',
  'Béni Abbès',
  'In Salah',
  'In Guezzam',
  'Touggourt',
  'Djanet',
  'El M\'Ghair',
  'El Meniaa',
] as const